repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: pre-commit-terraform
        name: pre-commit Terraform
        language: system
        entry: bash -c 'cd terraform && pre-commit run --all-files'
        require_serial: true
        verbose: true
      - id: pre-commit-python
        name: pre-commit Python
        language: system
        entry: bash -c 'cd airflow && pre-commit run --all-files'
        require_serial: true
        verbose: true
      - id: terraform-docs
        name: Terraform Documentation
        language: script
        entry: ./scripts/terraform_docs.sh
        require_serial: true
        verbose: true
