locals {
  namespace           = "data"
  airflow_helm_repo   = "https://github.com/afranzi/mini-data-platform.git"
  bitnami_helm_charts = "https://charts.bitnami.com/bitnami"
}

module "namespace" {
  source    = "../modules/k8s/namespace"
  namespace = local.namespace
}

# --- Airflow secrets (Story 2.1 / architecture D4) ----------------------------
# Generated by Terraform and written to Kubernetes Secrets in the `data`
# namespace. NEVER committed in plaintext (NFR3) — values live only in local
# state. Secret + key names match the official Apache chart's expectations so
# Story 2.3 can reference them via fernetKeySecretName / apiSecretKeySecretName /
# data.metadataSecretName with no renaming.

# Fernet key MUST be 32 url-safe-base64 bytes (random_password would be invalid).
resource "random_bytes" "fernet_key" {
  length = 32
}

resource "random_password" "api_secret_key" {
  length  = 32
  special = false
}

resource "random_password" "jwt_secret" {
  length  = 32
  special = false
}

# SimpleAuthManager admin password (Airflow 3).
resource "random_password" "admin" {
  length  = 24
  special = false
}

# Postgres metadata-DB password (replaces the previous plaintext "data").
# special = false keeps it safe inside the SQLAlchemy connection URL.
resource "random_password" "postgres" {
  length  = 24
  special = false
}

resource "kubernetes_secret" "airflow_config_credentials" {
  metadata {
    name      = "airflow-config-credentials"
    namespace = module.namespace.name
  }

  type = "Opaque"

  data = {
    # url-safe base64 to exactly match Python Fernet.generate_key() output
    "fernet-key"     = replace(replace(random_bytes.fernet_key.base64, "+", "-"), "/", "_")
    "api-secret-key" = random_password.api_secret_key.result
    "jwt-secret"     = random_password.jwt_secret.result
    "admin-password" = random_password.admin.result
  }
}

resource "kubernetes_secret" "airflow_metadata" {
  metadata {
    name      = "airflow-metadata"
    namespace = module.namespace.name
  }

  type = "Opaque"

  # Key `connection` is what the chart's data.metadataSecretName reads.
  # Service `postgres-postgresql` = bitnami chart, release "postgres".
  data = {
    "connection" = "postgresql://mini:${random_password.postgres.result}@postgres-postgresql.${module.namespace.name}.svc.cluster.local:5432/mini_data_platform"
  }
}

module "project" {
  source                     = "../modules/k8s/argocd/project"
  cluster_resource_allowlist = [{ group : "*", kind : "*" }]
  description                = "Data Platform projects"
  name                       = "mini-data-platform"
  namespaces                 = [local.namespace]
  repo_urls                  = [local.airflow_helm_repo, local.bitnami_helm_charts]
  depends_on                 = [module.argocd]
  namespace                  = module.argocd.namespace
}


module "application_db" {
  source           = "../modules/k8s/argocd/application"
  name             = "postgres"
  argocd_namespace = module.argocd.namespace
  namespace        = module.namespace.name
  project_name     = module.project.name
  repo_url         = local.bitnami_helm_charts
  chart            = "postgresql"
  target_revision  = "14.2.4"

  parameters = {
    "auth.database" : "mini_data_platform"
    "auth.username" : "mini"
    "auth.password" : "data"
  }
}


module "application" {
  source           = "../modules/k8s/argocd/application"
  name             = "airflow"
  argocd_namespace = module.argocd.namespace
  namespace        = module.namespace.name
  project_name     = module.project.name
  repo_url         = local.airflow_helm_repo
  path             = "helms/airflow"
  target_revision  = "HEAD"

  values = {
    airflow = {
      airflow = {
        extraEnv = [
          { name : "DATA_DB", value : "mini_data_platform" },
          { name : "DATA_USER", value : "mini" },
          { name : "DATA_PASSWORD", value : "data" },
        ]
      }
    }
  }
}
