locals {
  namespace           = "data"
  airflow_helm_repo   = "https://github.com/afranzi/mini-data-platform.git"
  bitnami_helm_charts = "https://charts.bitnami.com/bitnami"
}

module "namespace" {
  source    = "../modules/k8s/namespace"
  namespace = local.namespace
}

# --- Airflow secrets (Story 2.1 / architecture D4) ----------------------------
# Generated by Terraform and written to Kubernetes Secrets in the `data`
# namespace. NEVER committed in plaintext (NFR3) — values live only in local
# state. Secret + key names match the official Apache chart's expectations so
# Story 2.3 can reference them via fernetKeySecretName / apiSecretKeySecretName /
# data.metadataSecretName with no renaming.

# Fernet key MUST be 32 url-safe-base64 bytes (random_password would be invalid).
resource "random_bytes" "fernet_key" {
  length = 32
}

resource "random_password" "api_secret_key" {
  length  = 32
  special = false
}

resource "random_password" "jwt_secret" {
  length  = 32
  special = false
}

# SimpleAuthManager admin password (Airflow 3).
resource "random_password" "admin" {
  length  = 24
  special = false
}

# Postgres metadata-DB password (replaces the previous plaintext "data").
# special = false keeps it safe inside the SQLAlchemy connection URL.
resource "random_password" "postgres" {
  length  = 24
  special = false
}

resource "kubernetes_secret" "airflow_config_credentials" {
  metadata {
    name      = "airflow-config-credentials"
    namespace = module.namespace.name
  }

  type = "Opaque"

  data = {
    # url-safe base64 to exactly match Python Fernet.generate_key() output
    "fernet-key"     = replace(replace(random_bytes.fernet_key.base64, "+", "-"), "/", "_")
    "api-secret-key" = random_password.api_secret_key.result
    "jwt-secret"     = random_password.jwt_secret.result
    "admin-password" = random_password.admin.result
  }
}

resource "kubernetes_secret" "airflow_metadata" {
  metadata {
    name      = "airflow-metadata"
    namespace = module.namespace.name
  }

  type = "Opaque"

  # Key `connection` is what the chart's data.metadataSecretName reads.
  # Service `postgres-postgresql` = bitnami chart, release "postgres".
  data = {
    "connection" = "postgresql://mini:${random_password.postgres.result}@postgres-postgresql.${module.namespace.name}.svc.cluster.local:5432/mini_data_platform"
  }
}

# CeleryExecutor result backend (chart's data.resultBackendSecretName). Same DB
# as the metadata connection but with the SQLAlchemy `db+` prefix Celery expects
# — the chart does NOT derive this from metadataSecretName. Shares the single
# random_password.postgres so DB/metadata/result-backend never disagree.
resource "kubernetes_secret" "airflow_result_backend" {
  metadata {
    name      = "airflow-result-backend"
    namespace = module.namespace.name
  }

  type = "Opaque"

  data = {
    "connection" = "db+postgresql://mini:${random_password.postgres.result}@postgres-postgresql.${module.namespace.name}.svc.cluster.local:5432/mini_data_platform"
  }
}

module "project" {
  source                     = "../modules/k8s/argocd/project"
  cluster_resource_allowlist = [{ group : "*", kind : "*" }]
  description                = "Data Platform projects"
  name                       = "mini-data-platform"
  namespaces                 = [local.namespace]
  repo_urls                  = [local.airflow_helm_repo, local.bitnami_helm_charts]
  depends_on                 = [module.argocd]
  namespace                  = module.argocd.namespace
}


module "application_db" {
  source           = "../modules/k8s/argocd/application"
  name             = "postgres"
  argocd_namespace = module.argocd.namespace
  namespace        = module.namespace.name
  project_name     = module.project.name
  repo_url         = local.bitnami_helm_charts
  chart            = "postgresql"
  target_revision  = "14.2.4"

  parameters = {
    "auth.database" : "mini_data_platform"
    "auth.username" : "mini"
    # Reconciled to the generated password (NFR3) — matches the airflow-metadata
    # and airflow-result-backend connection secrets (one source: random_password.postgres).
    "auth.password" : random_password.postgres.result
    # bitnamilegacy image sources (FR18/D8) — frozen free images after the 2025
    # Bitnami catalog change. All overrides live here (single place, not values).
    "image.repository" : "bitnamilegacy/postgresql"
    "volumePermissions.image.repository" : "bitnamilegacy/os-shell"
    "metrics.image.repository" : "bitnamilegacy/postgres-exporter"
  }
}


module "application" {
  source           = "../modules/k8s/argocd/application"
  name             = "airflow"
  argocd_namespace = module.argocd.namespace
  namespace        = module.namespace.name
  project_name     = module.project.name
  repo_url         = local.airflow_helm_repo
  path             = "helms/airflow"
  target_revision  = "HEAD"

  # All chart config lives in helms/airflow/values.yaml (official-chart schema,
  # Story 2.3). No inline `values` here: the former DATA_* extraEnv was community
  # -chart vestigial (double-nested airflow.airflow.*) with no consumer in repo.

  # Secrets must exist before ArgoCD syncs the chart (architecture D4 ordering).
  depends_on = [
    kubernetes_secret.airflow_config_credentials,
    kubernetes_secret.airflow_metadata,
    kubernetes_secret.airflow_result_backend,
  ]
}
