apiVersion: v2
name: airflow
description: Universal Ranking Algorithm for Natural language Archive and Index
maintainers:
  - name: Albert Franzi
version: 8.8.0
appVersion: 2.6.3
dependencies:
  - name: airflow # https://artifacthub.io/packages/helm/airflow-helm/airflow
    version: 8.8.0
    repository: https://airflow-helm.github.io/charts #https://airflow.apache.org
